"""Created model Vaccination

Revision ID: 4b155698f0d6
Revises: 
Create Date: 2021-09-22 23:17:57.932887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b155698f0d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_card',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_shot_date', sa.DateTime()),
    sa.Column('second_shot_date', sa.DateTime()),
    sa.Column('vaccine_name', sa.String(length=255), nullable=False),
    sa.Column('health_unit_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccine_card')
    # ### end Alembic commands ###
